[workspace]
members = [
    "crates/debug",
    "crates/game",
    "crates/util",
    "examples/builder-mode",
    "tools/export-singletons",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/vswarte/chains-bindings"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
game = { path = "crates/game" }
util = { path = "crates/util" }
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
nalgebra-glm = "0.18"
nalgebra = "0.32"
tracing-panic = "0.1"
tracing-appender = "0.2.3"

[workspace.dependencies.windows]
version = "0.54"
features = [
    "Win32_Foundation",
	"Win32_System_Kernel",
	"Win32_System_Threading",
	"Win32_UI_WindowsAndMessaging",
	"Win32_UI_Input_KeyboardAndMouse",
	"Win32_System_Diagnostics_Debug",
]

[patch.crates-io]
libudis86-sys = { git = 'https://github.com/vars1ty/libudis86-sys.git' }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
