# Mapper file used to retrieve the fixed RVAs in the hardcoded location provider.

[[patterns]]
pattern = "ba ff 01 00 00 40 84 ff 74 ? 45 33 c0 e8 $ { ' }"
captures = ["", "APPLY_SPEFFECT"]

[[patterns]]
pattern = "ba ae 70 04 00 e8 $ { ' }"
captures = ["", "LOOKUP_MENU_TEXT"]

[[patterns]]
pattern = "ba d0 07 00 00 48 83 c4 28 e9 $ { ' }"
captures = ["", "PRESENT_MP_MESSAGE"]

[[patterns]]
pattern = "ba 36 00 00 00 49 8b ce e8 $ { ' }"
captures = ["", "MSB_GET_POINT_DATA_COUNT"]

[[patterns]]
pattern = "8d 56 0d 48 8b c8 e8 $ { ' }"
captures = ["", "MSB_GET_PARTS_DATA_COUNT"]

[[patterns]]
pattern = "4c 8b 73 28 ba 14 00 00 00 49 8b ce e8 $ { ' }"
captures = ["", "MSB_GET_EVENT_DATA_COUNT"]

[[patterns]]
pattern = "83 78 0c 06 74 ? 48 8b d3 48 8b cf e8 $ { ' }"
captures = ["", "SPAWN_DROPPED_ITEM"]

[[patterns]]
pattern = "48 8d 4d 07 e8 ? ? ? ? 48 8d 4d af e8 $ { ' }"
captures = ["", "GET_TARGET_MAP_ID"]

[[patterns]]
pattern = "40 53 48 83 ec 40 c7 44 24 50 00 00 00 00 48 8b d9 48 8b 89 90 01 00 00 0f 57 db f3 0f 10 05 f5 19 ea 02"
captures = ["CHR_INS_DEAD"]

[[patterns]]
pattern = "4c 8b ce 4c 8d 45 e7 48 8d 55 d7 48 8b cb e8 $ { ' }"
captures = ["", "INITIAL_SPAWN_POSITION"]

[[patterns]]
pattern = "4c 89 33 4c 89 73 08 48 8b d5 48 8d 4b 20 e8 $ {} 83 7f 1c 08 ' 7c ?"
captures = ["", "DROPPED_ITEM_CAP_CHECK"]

[[patterns]]
pattern = "44 8b cd 4c 8b c7 48 8b d6 8b cb e8 $ { ' }"
captures = ["", "TRANSFER_ITEM"]

[[patterns]]
pattern = "0f 29 4d 37 48 8d 45 67 48 89 45 7f 89 75 67 48 8d 55 07 48 8d 4d 67 e8 $ { ' }"
captures = ["", "SFX_SPAWN"]

[[patterns]]
pattern = "ba 58 00 00 02 e8 $ { ' }"
captures = ["", "WORLD_CAST_RAY"]

[[patterns]]
pattern = "4c 8b c0 48 8d 8f 30 01 00 00 48 8d 54 24 30 e8 $ { ' }"
captures = ["", "SPAWN_DROPPED_ITEM_VFX"]

[[patterns]]
pattern = "48 8d 55 c0 8b 45 e8 48 8d 4d d0 f2 0f 11 45 c0 89 45 c8 e8 $ { ' }"
captures = ["", "CONVERT_BLOCK_COORDS_TO_WORLD_COORDS"]

[[patterns]]
pattern = "48 8d 54 24 30 48 03 c8 66 c7 44 24 30 01 00 48 8d 05 $ { ' }"
captures = ["", "AI_LOCK_ON_TEAMTYPE_RELATIONS_TABLE"]

[[patterns]]
pattern = "44 88 44 24 30 48 8d 05 $ { ' } c6 44 24 32 00"
captures = ["", "DAMAGE_TEAMTYPE_RELATIONS_TABLE"]

[[patterns]]
pattern = "83 7a 4c ff 75 ? 33 d2 e8 $ { ' } e9 ? ? ? ?"
captures = ["", "UNEQUIP_ITEM"]

[[patterns]]
pattern = "45 8b 8f bc 00 00 00 4c 8d 45 c0 0f b6 d0 49 8b 4f 30 e8 $ { ' }"
captures = ["", "SPAWN_CHR"]

[[patterns]]
pattern = "48 8b d3 e8 $ { ' } 48 8b 5c 24 38 48 8b 03 48 89 87 18 02 00 00"
captures = ["", "NET_CHR_SYNC_SETUP_ENTITY_HANDLE"]

[[patterns]]
pattern = "80 bd a8 01 00 00 00 74 ? b2 01 48 8b cf e8 $ { ' } 48 8b cf e8 $ { ' }"
captures = ["", "CHR_FLAGS_UNK1", "CHR_FLAGS_UNK2"]
